export enum ErrorCode {
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  NOT_FOUND = 'NOT_FOUND',
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  GOAL_NOT_FOUND = 'GOAL_NOT_FOUND',
  INSUFFICIENT_BALANCE = 'INSUFFICIENT_BALANCE',
  TRANSACTION_FAILED = 'TRANSACTION_FAILED',
  SWAP_FAILED = 'SWAP_FAILED',
  INSUFFICIENT_LIQUIDITY = 'INSUFFICIENT_LIQUIDITY',
  GROW_MODE_DISABLED = 'GROW_MODE_DISABLED',
  PASSPORT_NOT_FOUND = 'PASSPORT_NOT_FOUND',
  WALRUS_STORE_FAILED = 'WALRUS_STORE_FAILED',
  WALRUS_RETRIEVE_FAILED = 'WALRUS_RETRIEVE_FAILED',
  SEAL_ENCRYPT_FAILED = 'SEAL_ENCRYPT_FAILED',
  SEAL_DECRYPT_FAILED = 'SEAL_DECRYPT_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}

export interface ApiError {
  error: {
    code: ErrorCode;
    message: string;
    details?: unknown;
  };
}
